issuesSections:
  - title: PSDocs
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs
  - title: PSModules
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-Modules
  - title: DSC
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-DSC
  - title: GuestConfig
    filters: is:open repo:MicrosoftDocs/azure-docs label:machine-configuration/svc
  - title: Cloud-Docs
    filters: is:open repo:MicrosoftDocs/azure-docs label:cloud-shell/svc
  - title: Cloud-Code
    filters: is:open repo:Azure/CloudShell label:Area-documentation
  - title: Blog
    filters: is:open repo:PowerShell/Community-Blog
  - title: AzPS
    filters: is:open repo:MicrosoftDocs/azure-docs-powershell
  - title: WindowsPS
    filters: is:open repo:MicrosoftDocs/windows-powershell-docs
    limit: 50 # optional limit per section
prSections:
  - title: PSDocs
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs
  - title: PSModules
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-Modules
  - title: Blog
    filters: is:open repo:PowerShell/Community-Blog
  - title: DSC
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-DSC
  - title: GuestConfig
    filters: is:open repo:MicrosoftDocs/azure-docs label:machine-configuration/svc
  - title: Cloud-Docs
    filters: is:open repo:MicrosoftDocs/azure-docs label:cloud-shell/svc
  - title: Cloud-Code
    filters: is:open repo:Azure/CloudShell
  - title: AzPS
    filters: is:open repo:MicrosoftDocs/azure-docs-powershell
  - title: WindowsPS
    filters: is:open repo:MicrosoftDocs/windows-powershell-docs
    limit: 50 # optional limit per section
defaults:
  prsLimit: 20 # global limit
  issuesLimit: 50 # global limit
  preview:
    open: true
    width: 60
theme:
  colors:
    text:
      primary: "#F7F1FF"
      secondary: "#5AD4E6"
      inverted: "#CCCCCC"
      faint: "#3E4057"
      warning: "#FC618D"
      success: "#7BD88F"
    background:
      selected: "#535155"
    border:
      primary: "#948AE3"
      secondary: "#7BD88F"
      faint: "#3E4057"
