# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
issuesSections:
  - title: PSDocs
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs
  - title: PSModules
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-Modules
  - title: Gallery
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-PSGet
  - title: DSC
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-DSC
  - title: GuestConfig
    filters: is:open repo:MicrosoftDocs/azure-docs label:machine-configuration/svc
  - title: Cloud-Docs
    filters: is:open repo:MicrosoftDocs/azure-docs label:cloud-shell/svc
  - title: Cloud-Code
    filters: is:open repo:Azure/CloudShell label:Area-documentation
  - title: Blog
    filters: is:open repo:PowerShell/Community-Blog
  - title: AzPS
    filters: is:open repo:MicrosoftDocs/azure-docs-powershell
  - title: WindowsPS
    filters: is:open repo:MicrosoftDocs/windows-powershell-docs
    limit: 20
prSections:
  - title: PSDocs
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs
  - title: PSModules
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-Modules
  - title: Gallery
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-PSGet
  - title: DSC
    filters: is:open repo:MicrosoftDocs/PowerShell-Docs-DSC
  - title: PS SDK
    filters: is:open repo:MicrosoftDocs/powershell-docs-sdk-dotnet
  - title: GuestConfig
    filters: is:open repo:MicrosoftDocs/azure-docs-pr repo:MicrosoftDocs/azure-docs label:machine-configuration/svc
  - title: Cloud-Docs
    filters: is:open repo:MicrosoftDocs/azure-docs-pr repo:MicrosoftDocs/azure-docs label:cloud-shell/svc
  - title: Cloud-Code
    filters: is:open repo:Azure/CloudShell
  - title: Blog
    filters: is:open repo:PowerShell/Community-Blog
  - title: AzPS
    filters: is:open repo:MicrosoftDocs/azure-docs-powershell
  - title: WindowsPS
    filters: is:open repo:MicrosoftDocs/windows-powershell-docs
    limit: 20
defaults:
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true
    width: 60
  layout:
    prs:
      repo:
        hidden: true
      title:
        grow: true
    issues:
      repo:
        hidden: true
      title:
        grow: true
keybindings:
  universal:
    - key: pgup
      builtin: pageUp
    - key: pgdown
      builtin: pageDown
theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
      showSeparator: true
  colors:
    text:
      primary: '#f7f1ff'
      secondary: '#5ad4e6'
      inverted: '#282a36'
      faint: '#ffb86c'
      success: '#50fa7b'
      warning: '#ff5555'
      error: '#ff5555'
    background:
      selected: '#39386b'
    border:
      primary: '#383b5b'
      secondary: '#39386b'
      faint: '#2b2b40'
